# Generated by Django 2.2.28 on 2023-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='rien', max_length=200),
        ),
        migrations.AddField(
            model_name='equipement',
            name='description',
            field=models.CharField(default='rien', max_length=200),
        ),
    ]
