# Generated by Django 2.2.28 on 2023-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231116_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(default='rien', max_length=400),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='description',
            field=models.CharField(default='rien', max_length=400),
        ),
    ]
